version: '3'
name: 'Otto'
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      vpcbr:
        ipv4_address: 172.18.0.2

  flask-web:
    image: flask
    container_name: flask
    ports:
      - 5000:5000
    volumes:
      - ./flask:/code
    networks:
      vpcbr:
        ipv4_address: 172.18.0.24
    env_file:
      - flask-variables.env
    depends_on:
      - mosquitto
      - broker

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      vpcbr:
        ipv4_address: 172.18.0.25

  broker:
    image: confluentinc/cp-kafka:5.5.0
    container_name: broker
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      vpcbr:
        ipv4_address: 172.18.0.26

  proxy-mqtt:
    image: proxy
    container_name: proxy
    volumes:
      - ./proxy:/app
    networks:
      vpcbr:
        ipv4_address: 172.18.0.27
    env_file:
      - flask-variables.env
    depends_on:
      - mosquitto
      - broker

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: "172.18.0.0/16"
          gateway: "172.18.0.1"
